### ISSUE TITLE
USER STORY: Submit a Poll Response

### ISSUE THREAD

**Issue by SerjMartin** [SerjMartin/love-runing#2]
In order to **provide my option with regards to a certain running topic or event** as a **user**, I can **select and submit an answer from the poll**

# Acceptance Criteria
* The option should be provided as a checkbox
* The checkbox should be "checked" by default
* In option should appear next  to submit button
* After submitting the default submission confirmation should be adjusted to include the user name

# Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name  of the submitter
- [ ] Create the new field in the model to track the user name
- [ ] Update the controller function
- [ ] Update the unit test scripts
- [ ] Test the functionality
