### ISSUE TITLE
USER STORY: Publish a Poll

### ISSUE THREAD

**Issue by SerjMartin** [SerjMartin/love-runing#3]
In order to **automatically hide the poll** as an **administrator**, I can **pick the expiry date while publishing the poll**

# Acceptance Criteria
* The poll should disappear at 11:59 on the target date
* The real estate of the "Poll" should be reserved on the home page. a message that says "stay Tuned, a new poll is coming soon" should appear if no other Poll is active
* The administrator expiry date should be at least 3  days after the current date.

# Tasks
- [ ] Update the admin module view: the poll design (HTML and CSS) to include a date picker
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a JavaScript to validate the expired date is at least after 3 days.
- [ ] Create a job to check expired Polls every day at 11:59 PM and hide them
- [ ] Update the controller function
- [ ] Update unit test script
- [ ] Test the functionality
